language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $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
 local_dir: dist
 on:
   branch: main